-- Add more train stations
INSERT INTO public.stations (name, code, city, state) VALUES
  ('Mumbai Central', 'MMCT', 'Mumbai', 'Maharashtra'),
  ('Ahmedabad Junction', 'ADI', 'Ahmedabad', 'Gujarat'),
  ('Rajkot Junction', 'RJT', 'Rajkot', 'Gujarat'),
  ('Surat', 'ST', 'Surat', 'Gujarat'),
  ('Vadodara Junction', 'BRC', 'Vadodara', 'Gujarat'),
  ('Indore Junction', 'INDB', 'Indore', 'Madhya Pradesh'),
  ('Bhopal Junction', 'BPL', 'Bhopal', 'Madhya Pradesh'),
  ('Jabalpur', 'JBP', 'Jabalpur', 'Madhya Pradesh'),
  ('Nagpur', 'NGP', 'Nagpur', 'Maharashtra'),
  ('Pune Junction', 'PUNE', 'Pune', 'Maharashtra'),
  ('Chennai Central', 'MAS', 'Chennai', 'Tamil Nadu'),
  ('Coimbatore Junction', 'CBE', 'Coimbatore', 'Tamil Nadu'),
  ('Madurai Junction', 'MDU', 'Madurai', 'Tamil Nadu'),
  ('Trivandrum Central', 'TVC', 'Thiruvananthapuram', 'Kerala'),
  ('Kochi Central', 'ERS', 'Kochi', 'Kerala'),
  ('Calicut', 'CLT', 'Kozhikode', 'Kerala'),
  ('Hyderabad Deccan', 'HYB', 'Hyderabad', 'Telangana'),
  ('Secunderabad Junction', 'SC', 'Secunderabad', 'Telangana'),
  ('Vijayawada Junction', 'BZA', 'Vijayawada', 'Andhra Pradesh'),
  ('Visakhapatnam', 'VSKP', 'Visakhapatnam', 'Andhra Pradesh'),
  ('Jaipur Junction', 'JP', 'Jaipur', 'Rajasthan'),
  ('Jodhpur Junction', 'JU', 'Jodhpur', 'Rajasthan'),
  ('Udaipur City', 'UDZ', 'Udaipur', 'Rajasthan'),
  ('Ajmer Junction', 'AII', 'Ajmer', 'Rajasthan'),
  ('Lucknow', 'LJN', 'Lucknow', 'Uttar Pradesh'),
  ('Kanpur Central', 'CNB', 'Kanpur', 'Uttar Pradesh'),
  ('Varanasi Junction', 'BSB', 'Varanasi', 'Uttar Pradesh'),
  ('Allahabad Junction', 'ALD', 'Allahabad', 'Uttar Pradesh'),
  ('Patna Junction', 'PNBE', 'Patna', 'Bihar'),
  ('Gaya Junction', 'GAYA', 'Gaya', 'Bihar'),
  ('Ranchi', 'RNC', 'Ranchi', 'Jharkhand'),
  ('Dhanbad Junction', 'DHN', 'Dhanbad', 'Jharkhand'),
  ('Howrah Junction', 'HWH', 'Howrah', 'West Bengal'),
  ('Sealdah', 'SDAH', 'Kolkata', 'West Bengal'),
  ('Bhubaneswar', 'BBS', 'Bhubaneswar', 'Odisha'),
  ('Cuttack', 'CTC', 'Cuttack', 'Odisha'),
  ('Guwahati', 'GHY', 'Guwahati', 'Assam'),
  ('Dibrugarh', 'DBRG', 'Dibrugarh', 'Assam'),
  ('Agartala', 'AGTL', 'Agartala', 'Tripura'),
  ('Silchar', 'SCL', 'Silchar', 'Assam')
ON CONFLICT (code) DO NOTHING;